version: '3.8'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=Abcd_1234
    ports:
      - "27017:27017"
    volumes:
      - ./db_mongo_new:/data/db

  app:
    build: .
    restart: unless-stopped
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_URI=mongodb://mongo:Abcd_1234@mongodb:27017/url_shortner?authSource=admin
      - PRODUCTION_URL=http://localhost:8000/
    depends_on:
      - mongo
