version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_postgres:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/url_shortener
      - PRODUCTION_URL=http://localhost:8000/
    depends_on:
      - postgres
    entrypoint: ["sh", "./waitForDb.sh"]
